openapi: "3.0.1"
info:
  title: "API Documentation"
  version: "1.0"
paths:
  /slurm/{version}/job/submit:
    post:
      summary: "提交作业接口"
      parameters:
      - name: "version"
        in: "path"
        description: "版本"
        required: true
        schema:
          type: "string"
      - name: "X-SLURM-USER-TOKEN"
        in: "header"
        description: "鉴权"
        required: true
        schema: {}
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              properties:
                job:
                  type: "object"
                  properties:
                    cpus_per_task:
                      type: "integer"
                      description: "每个任务所需的CPU数量"
                    tasks_per_node:
                      type: "integer"
                      description: "每个节点调用的任务数量"
                    memory_per_cpu:
                      type: "object"
                      properties:
                        set:
                          type: "boolean"
                          description: "是否设置参数值"
                        infinite:
                          type: "boolean"
                          description: "是否为无穷"
                        number:
                          type: "integer"
                          description: "参数值"
                          format: "int64"
                      description: "每个节点所需的CPU"
                    memory_per_node:
                      type: "object"
                      properties:
                        set:
                          type: "boolean"
                          description: "是否设置参数值"
                        infinite:
                          type: "boolean"
                          description: "是否为无穷"
                        number:
                          type: "integer"
                          description: "参数值"
                          format: "int64"
                      description: "每个节点所需的内存"
                    current_working_directory:
                      type: "string"
                      description: "作业使用的工作目录"
                    standard_output:
                      type: "string"
                      description: "输出文件路径"
                    standard_error:
                      type: "string"
                      description: "错误输出文件路径"
                    standard_input:
                      type: "string"
                      description: "输入文件路径"
                    begin_time:
                      type: "object"
                      properties:
                        set:
                          type: "boolean"
                          description: "是否设置参数值"
                        infinite:
                          type: "boolean"
                          description: "是否为无穷"
                        number:
                          type: "integer"
                          description: "参数值"
                          format: "int64"
                      description: "作业开始的时间"
                    end_time:
                      type: "integer"
                      description: "作业结束的时间"
                      format: "int64"
                    excluded_nodes:
                      type: "array"
                      description: "不使用的节点列表"
                      items:
                        type: "string"
                    required_nodes:
                      type: "array"
                      description: "特定的节点列表"
                      items:
                        type: "string"
                    group_id:
                      type: "integer"
                      description: "组ID"
                    user_id:
                      type: "integer"
                      description: "用户ID"
                    account:
                      type: "string"
                      description: "账号"
                    name:
                      type: "string"
                      description: "作业名称"
                    nodes:
                      type: "string"
                      description: "运行节点数量"
                    partition:
                      type: "string"
                      description: "分配给作业的分区"
                    timeLimit:
                      type: "object"
                      properties:
                        set:
                          type: "boolean"
                          description: "是否设置参数值"
                        infinite:
                          type: "boolean"
                          description: "是否为无穷"
                        number:
                          type: "integer"
                          description: "参数值"
                      description: "作业的时间限制"
                    script:
                      type: "string"
                      description: "作业批处理脚本"
                    exclusive:
                      type: "boolean"
                      description: "资源是否独占"
                    qos:
                      type: "string"
                      description: "分配给作业的服务质量"
                    priority:
                      type: "object"
                      properties:
                        set:
                          type: "boolean"
                          description: "是否设置参数值"
                        infinite:
                          type: "boolean"
                          description: "是否为无穷"
                        number:
                          type: "integer"
                          description: "参数值"
                      description: "作业的优先级"
                    dependency:
                      type: "string"
                      description: "其他作业必须满足某些条件才能开始此作业"
                    environment:
                      type: "array"
                      description: "作业的环境变量"
                      items:
                        type: "string"
                  description: ""
              description: "提交任务请求对象"
      responses:
        "200":
          description: "作业相关信息对象"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  job_id:
                    type: "integer"
                    description: "作业ID"
                  step_id:
                    type: "string"
                    description: "步骤ID"
                  job_submit_user_msg:
                    type: "string"
                    description: "用户提交作业的信息"
                  meta:
                    type: "object"
                    properties:
                      slurm:
                        type: "object"
                        properties:
                          cluster:
                            type: "string"
                            description: "集群名称"
                          release:
                            type: "string"
                            description: "版本发布信息"
                          version:
                            type: "object"
                            properties:
                              major:
                                type: "string"
                                description: "主版本号"
                              minor:
                                type: "string"
                                description: "次版本号"
                              micro:
                                type: "string"
                                description: "修订版本号"
                            description: "版本信息"
                        description: "Slurm相关信息"
                      plugin:
                        type: "object"
                        properties:
                          accounting_storage:
                            type: "string"
                            description: "会计存储"
                          data_parser:
                            type: "string"
                            description: "数据解析器"
                          name:
                            type: "string"
                            description: "插件名称"
                          type:
                            type: "string"
                            description: "插件类型"
                        description: "插件信息"
                      client:
                        type: "object"
                        properties:
                          source:
                            type: "string"
                            description: "来源"
                          user:
                            type: "string"
                            description: "用户"
                          group:
                            type: "string"
                            description: "用户组"
                        description: "客户端信息"
                      command:
                        type: "array"
                        description: "命令列表"
                        items:
                          type: "string"
                    description: "元信息"
                  errors:
                    type: "array"
                    description: "错误信息"
                    items:
                      type: "object"
                      properties:
                        error_number:
                          type: "integer"
                          description: "错误编号"
                        description:
                          type: "string"
                          description: "错误描述"
                        source:
                          type: "string"
                          description: "错误来源"
                        error:
                          type: "string"
                          description: "错误信息"
                      description: "Slurm作业响应错误对象"
                  warnings:
                    type: "array"
                    description: "警告信息"
                    items:
                      type: "object"
                      properties:
                        description:
                          type: "string"
                          description: "警告描述"
                        source:
                          type: "string"
                          description: "警告来源"
                      description: "作业响应警告对象"
                  result:
                    type: "object"
                    properties:
                      job_id:
                        type: "integer"
                        description: "作业ID"
                      error_code:
                        type: "integer"
                        description: "错误代码"
                      step_id:
                        type: "string"
                        description: "步骤ID"
                      job_submit_user_msg:
                        type: "string"
                        description: "用户提交作业的信息"
                      error:
                        type: "string"
                        description: "错误信息"
                    description: "结果信息"
                description: "作业相关信息对象"
components:
  schemas:
    长整型类参数设置对象:
      type: "object"
      properties:
        set:
          type: "boolean"
          description: "是否设置参数值"
        infinite:
          type: "boolean"
          description: "是否为无穷"
        number:
          type: "integer"
          description: "参数值"
          format: "int64"
      description: "作业开始的时间"
    整型类参数设置对象:
      type: "object"
      properties:
        set:
          type: "boolean"
          description: "是否设置参数值"
        infinite:
          type: "boolean"
          description: "是否为无穷"
        number:
          type: "integer"
          description: "参数值"
      description: "作业的优先级"
    com.zznode.hcpsp.api.feign.slurm.job.vo.SubmitJobRequest.Job:
      type: "object"
      properties:
        cpus_per_task:
          type: "integer"
          description: "每个任务所需的CPU数量"
        tasks_per_node:
          type: "integer"
          description: "每个节点调用的任务数量"
        memory_per_cpu:
          type: "object"
          properties:
            set:
              type: "boolean"
              description: "是否设置参数值"
            infinite:
              type: "boolean"
              description: "是否为无穷"
            number:
              type: "integer"
              description: "参数值"
              format: "int64"
          description: "每个节点所需的CPU"
        memory_per_node:
          type: "object"
          properties:
            set:
              type: "boolean"
              description: "是否设置参数值"
            infinite:
              type: "boolean"
              description: "是否为无穷"
            number:
              type: "integer"
              description: "参数值"
              format: "int64"
          description: "每个节点所需的内存"
        current_working_directory:
          type: "string"
          description: "作业使用的工作目录"
        standard_output:
          type: "string"
          description: "输出文件路径"
        standard_error:
          type: "string"
          description: "错误输出文件路径"
        standard_input:
          type: "string"
          description: "输入文件路径"
        begin_time:
          type: "object"
          properties:
            set:
              type: "boolean"
              description: "是否设置参数值"
            infinite:
              type: "boolean"
              description: "是否为无穷"
            number:
              type: "integer"
              description: "参数值"
              format: "int64"
          description: "作业开始的时间"
        end_time:
          type: "integer"
          description: "作业结束的时间"
          format: "int64"
        excluded_nodes:
          type: "array"
          description: "不使用的节点列表"
          items:
            type: "string"
        required_nodes:
          type: "array"
          description: "特定的节点列表"
          items:
            type: "string"
        group_id:
          type: "integer"
          description: "组ID"
        user_id:
          type: "integer"
          description: "用户ID"
        account:
          type: "string"
          description: "账号"
        name:
          type: "string"
          description: "作业名称"
        nodes:
          type: "string"
          description: "运行节点数量"
        partition:
          type: "string"
          description: "分配给作业的分区"
        timeLimit:
          type: "object"
          properties:
            set:
              type: "boolean"
              description: "是否设置参数值"
            infinite:
              type: "boolean"
              description: "是否为无穷"
            number:
              type: "integer"
              description: "参数值"
          description: "作业的时间限制"
        script:
          type: "string"
          description: "作业批处理脚本"
        exclusive:
          type: "boolean"
          description: "资源是否独占"
        qos:
          type: "string"
          description: "分配给作业的服务质量"
        priority:
          type: "object"
          properties:
            set:
              type: "boolean"
              description: "是否设置参数值"
            infinite:
              type: "boolean"
              description: "是否为无穷"
            number:
              type: "integer"
              description: "参数值"
          description: "作业的优先级"
        dependency:
          type: "string"
          description: "其他作业必须满足某些条件才能开始此作业"
        environment:
          type: "array"
          description: "作业的环境变量"
          items:
            type: "string"
      description: ""
    com.zznode.hcpsp.api.feign.slurm.entity.SlurmMeta.Slurm.Version:
      type: "object"
      properties:
        major:
          type: "string"
          description: "主版本号"
        minor:
          type: "string"
          description: "次版本号"
        micro:
          type: "string"
          description: "修订版本号"
      description: "版本信息"
    com.zznode.hcpsp.api.feign.slurm.entity.SlurmMeta.Slurm:
      type: "object"
      properties:
        cluster:
          type: "string"
          description: "集群名称"
        release:
          type: "string"
          description: "版本发布信息"
        version:
          type: "object"
          properties:
            major:
              type: "string"
              description: "主版本号"
            minor:
              type: "string"
              description: "次版本号"
            micro:
              type: "string"
              description: "修订版本号"
          description: "版本信息"
      description: "Slurm相关信息"
    com.zznode.hcpsp.api.feign.slurm.entity.SlurmMeta.Plugin:
      type: "object"
      properties:
        accounting_storage:
          type: "string"
          description: "会计存储"
        data_parser:
          type: "string"
          description: "数据解析器"
        name:
          type: "string"
          description: "插件名称"
        type:
          type: "string"
          description: "插件类型"
      description: "插件信息"
    com.zznode.hcpsp.api.feign.slurm.entity.SlurmMeta.Client:
      type: "object"
      properties:
        source:
          type: "string"
          description: "来源"
        user:
          type: "string"
          description: "用户"
        group:
          type: "string"
          description: "用户组"
      description: "客户端信息"
    Slurm作业响应元信息对象:
      type: "object"
      properties:
        slurm:
          type: "object"
          properties:
            cluster:
              type: "string"
              description: "集群名称"
            release:
              type: "string"
              description: "版本发布信息"
            version:
              type: "object"
              properties:
                major:
                  type: "string"
                  description: "主版本号"
                minor:
                  type: "string"
                  description: "次版本号"
                micro:
                  type: "string"
                  description: "修订版本号"
              description: "版本信息"
          description: "Slurm相关信息"
        plugin:
          type: "object"
          properties:
            accounting_storage:
              type: "string"
              description: "会计存储"
            data_parser:
              type: "string"
              description: "数据解析器"
            name:
              type: "string"
              description: "插件名称"
            type:
              type: "string"
              description: "插件类型"
          description: "插件信息"
        client:
          type: "object"
          properties:
            source:
              type: "string"
              description: "来源"
            user:
              type: "string"
              description: "用户"
            group:
              type: "string"
              description: "用户组"
          description: "客户端信息"
        command:
          type: "array"
          description: "命令列表"
          items:
            type: "string"
      description: "元信息"
    Slurm作业响应错误对象:
      type: "object"
      properties:
        error_number:
          type: "integer"
          description: "错误编号"
        description:
          type: "string"
          description: "错误描述"
        source:
          type: "string"
          description: "错误来源"
        error:
          type: "string"
          description: "错误信息"
      description: "Slurm作业响应错误对象"
    作业响应警告对象:
      type: "object"
      properties:
        description:
          type: "string"
          description: "警告描述"
        source:
          type: "string"
          description: "警告来源"
      description: "作业响应警告对象"
    com.zznode.hcpsp.api.feign.slurm.job.vo.SubmitJobResponse.Result:
      type: "object"
      properties:
        job_id:
          type: "integer"
          description: "作业ID"
        error_code:
          type: "integer"
          description: "错误代码"
        step_id:
          type: "string"
          description: "步骤ID"
        job_submit_user_msg:
          type: "string"
          description: "用户提交作业的信息"
        error:
          type: "string"
          description: "错误信息"
      description: "结果信息"
